[package]
name = "api"
version = "0.1.0"
authors = ["wicki <krywicki2325@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web="3.3"
serde={version="1.0", features=["derive"]}