version: "3.8"
services:
    mongodb:
        image: mongo
        hostname: mongo
        ports:
            - "27017:27017"
        networks:
            - db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin

    mongodb-seed:
        build: ./mongodb-seed
        volumes:
            - "./mongodb-seed:/seed"
        depends_on:
            - mongodb
        networks:
            - db
        environment:
            DB_USERNAME: admin
            DB_PASSWORD: admin

    mongo-express:
        image: mongo-express
        depends_on:
            - mongodb
        ports:
            - "8081:8081"
        networks:
            - db
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin

networks:
    db:
        name: db
